

    return response.status(403).send({
      message: "Failed",
    });



    ...

    .catch((err) => {
      return response.status(403).send({
        message: err.message || err || "Failed",
      });
    });